version: '3'
services:
  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    container_name: chartmuseum
    networks:
     - chartmuseum-net
    ports:
     - 8080:8080
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: local 
      STORAGE_LOCAL_ROOTDIR: /var/data

networks:
  chartmuseum-net:

